<template>
<div class="container">
 <article class="message">
        <div class="message-header">
            <p>Skupstina stanara zakazana za 17.08 <span></span></p>
            <p class="is-size-7 user_seen">18 ljudi je videlo <i class="fas fa-eye"></i></p>
            <button class="delete" aria-label="delete"></button>
        </div>
        <div class="message-body">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Pellentesque risus mi</strong>, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum <a>felis venenatis</a> efficitur. Aenean ac <em>eleifend lacus</em>, in mollis lectus. Donec sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque. Donec dui urna, vehicula et sem eget, facilisis sodales sem.
        </div>
    <div class="message-footer">
        <span class="message_date message-body is-size-7">28.2.2018</span>   <span class="message_time message-body is-size-7">17:52h</span> 
        <div class="footer_buttons is-pulled-right">
            <button class="button is-primary is-inverted" @click="displayNotification" :disabled="false">Like</button><button class="button is-danger is-inverted" @click="displayNotificationErr" :disabled="false">Dislike</button>
        </div>    
        
    </div>
    <div class="notification is-primary">
        <button class="delete"></button>
        <strong>Oznacili ste da vam se svidja poruka!</strong>
      </div>
      <div class="notification is-danger">
        <button class="delete"></button>
        <strong>Oznacili ste da vam se ne svidja poruka!</strong>
      </div>
      <vue-snotify></vue-snotify>
</article>
<!-- message -->

 <article class="message">
        <div class="message-header">
            <p>Skupstina stanara zakazana za 17.08 <span></span></p>
            <p class="is-size-7 user_seen">18 ljudi je videlo <i class="fas fa-eye"></i></p>
            <button class="delete" aria-label="delete"></button>
        </div>
        <div class="message-body">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Pellentesque risus mi</strong>, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum <a>felis venenatis</a> efficitur. Aenean ac <em>eleifend lacus</em>, in mollis lectus. Donec sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque. Donec dui urna, vehicula et sem eget, facilisis sodales sem.
        </div>
    <div class="message-footer">
        <span class="message_date message-body is-size-7">28.2.2018</span>   <span class="message_time message-body is-size-7">17:52h</span> 
        <div class="footer_buttons is-pulled-right">
            <button class="button is-primary is-inverted" @click="displayNotification" :disabled="false">Like</button><button class="button is-danger is-inverted" @click="displayNotificationErr" :disabled="false">Dislike</button>
        </div>    
        
    </div>
    <div class="notification is-primary">
        <button class="delete"></button>
        <strong>Oznacili ste da vam se svidja poruka!</strong>
      </div>
      <div class="notification is-danger">
        <button class="delete"></button>
        <strong>Oznacili ste da vam se ne svidja poruka!</strong>
      </div>
      <vue-snotify></vue-snotify>
</article>
<!-- message -->

 <article class="message">
        <div class="message-header">
            <p>Skupstina stanara zakazana za 17.08 <span></span></p>
            <p class="is-size-7 user_seen">18 ljudi je videlo <i class="fas fa-eye"></i></p>
            <button class="delete" aria-label="delete"></button>
        </div>
        <div class="message-body">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Pellentesque risus mi</strong>, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum <a>felis venenatis</a> efficitur. Aenean ac <em>eleifend lacus</em>, in mollis lectus. Donec sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque. Donec dui urna, vehicula et sem eget, facilisis sodales sem.
        </div>
    <div class="message-footer">
        <span class="message_date message-body is-size-7">28.2.2018</span>   <span class="message_time message-body is-size-7">17:52h</span> 
        <div class="footer_buttons is-pulled-right">
            <button class="button is-primary is-inverted" @click="displayNotification" :disabled="false">Like</button><button class="button is-danger is-inverted" @click="displayNotificationErr" :disabled="false">Dislike</button>
        </div>    
        
    </div>
    <div class="notification is-primary">
        <button class="delete"></button>
        <strong>Oznacili ste da vam se svidja poruka!</strong>
      </div>
      <div class="notification is-danger">
        <button class="delete"></button>
        <strong>Oznacili ste da vam se ne svidja poruka!</strong>
      </div>
      <vue-snotify></vue-snotify>
</article>
<!-- message -->

 <article class="message">
        <div class="message-header">
            <p>Skupstina stanara zakazana za 17.08 <span></span></p>
            <p class="is-size-7 user_seen">18 ljudi je videlo <i class="fas fa-eye"></i></p>
            <button class="delete" aria-label="delete"></button>
        </div>
        <div class="message-body">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Pellentesque risus mi</strong>, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum <a>felis venenatis</a> efficitur. Aenean ac <em>eleifend lacus</em>, in mollis lectus. Donec sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque. Donec dui urna, vehicula et sem eget, facilisis sodales sem.
        </div>
    <div class="message-footer">
        <span class="message_date message-body is-size-7">28.2.2018</span>   <span class="message_time message-body is-size-7">17:52h</span> 
        <div class="footer_buttons is-pulled-right">
            <button class="button is-primary is-inverted" @click="displayNotification" :disabled="false">Like</button><button class="button is-danger is-inverted" @click="displayNotificationErr" :disabled="false">Dislike</button>
        </div>    
        
    </div>
    <div class="notification is-primary">
        <button class="delete"></button>
        <strong>Oznacili ste da vam se svidja poruka!</strong>
      </div>
      <div class="notification is-danger">
        <button class="delete"></button>
        <strong>Oznacili ste da vam se ne svidja poruka!</strong>
      </div>
      <vue-snotify></vue-snotify>
</article>
</div>

</template>

<script>
    import Snotify from 'vue-snotify';
    import 'vue-snotify/styles/material.css';

    Vue.use(Snotify);
    export default {
        mounted() {
            console.log('Component mounted.')
        },
        methods: {
            displayNotification: function() {
                this.$snotify.success('Liked! :)');

            },
            displayNotificationErr: function() {
                this.$snotify.error('Disiked! :(');

            }
        }
    }
</script>